import { type AnyExtension, Extension, getSchema, Node } from "@tiptap/core";
import CodeBlock from "@tiptap/extension-code-block";
import Highlight from "@tiptap/extension-highlight";
import HorizontalRule from "@tiptap/extension-horizontal-rule";
import Link from "@tiptap/extension-link";
import { TaskItem, TaskList } from "@tiptap/extension-list";
import { Mathematics } from "@tiptap/extension-mathematics";
import { TableKit } from "@tiptap/extension-table";
import TextAlign from "@tiptap/extension-text-align";
import UnderlineExtension from "@tiptap/extension-underline";
import StarterKit from "@tiptap/starter-kit";

export const tiptapDocumentYjsField = "default";

/**
 * A source reference inside a document. Holds the workspace item id rather than
 * the ref the assistant cited with: refs belong to one chat turn, and documents
 * outlive them. The label is stored alongside so rendering needs no lookup and
 * a deleted source still reads as prose.
 */
const Citation = Node.create({
	name: "citation",
	group: "inline",
	inline: true,
	atom: true,

	addAttributes() {
		return {
			itemId: { default: null, parseHTML: (el) => el.getAttribute("data-item-id") },
			label: { default: null, parseHTML: (el) => el.textContent?.trim() || null },
			pageNumber: {
				default: null,
				parseHTML: (el) => {
					const page = Number(el.getAttribute("data-page"));
					return Number.isInteger(page) && page > 0 ? page : null;
				},
			},
		};
	},

	parseHTML() {
		return [{ tag: "citation[data-item-id]" }];
	},

	renderHTML({ node }) {
		return [
			"citation",
			{
				"data-item-id": node.attrs.itemId,
				...(node.attrs.pageNumber ? { "data-page": String(node.attrs.pageNumber) } : {}),
			},
			node.attrs.label ?? "Source",
		];
	},
});
export const tiptapDocumentAiRefAttribute = "aiRef";

const DocumentAiRef = Extension.create({
	name: "documentAiRef",

	addGlobalAttributes() {
		const blockTypes = this.extensions
			.filter(
				(extension) =>
					extension.type === "node" &&
					typeof extension.config?.group === "string" &&
					extension.config.group.split(/\s+/).includes("block"),
			)
			.map((extension) => extension.name);

		return [
			{
				types: blockTypes,
				attributes: {
					[tiptapDocumentAiRefAttribute]: {
						default: null,
						// AI refs are generated by the document session. Pasted or model-authored
						// HTML must not be able to duplicate or choose them.
						parseHTML: () => null,
						renderHTML: (attributes: Record<string, unknown>) => {
							const ref = attributes[tiptapDocumentAiRefAttribute];
							return typeof ref === "string" && ref ? { "data-ref": ref } : {};
						},
					},
				},
			},
		];
	},
});

/**
 * Server-side code block extension. The editor swaps in `CodeBlockShiki`,
 * which extends the same `codeBlock` node spec, so JSON snapshots stay
 * compatible between kernel preview/session code and the live editor.
 */
export const tiptapDocumentKernelCodeBlock = CodeBlock;

export function getTiptapDocumentSchemaExtensions({
	codeBlock = tiptapDocumentKernelCodeBlock,
}: {
	codeBlock?: AnyExtension;
} = {}) {
	return [
		DocumentAiRef,
		Citation,
		StarterKit.configure({
			heading: {
				levels: [1, 2, 3, 4],
			},
			codeBlock: false,
			horizontalRule: false,
			link: false,
			underline: false,
			undoRedo: false,
		}),
		codeBlock,
		HorizontalRule,
		UnderlineExtension,
		Highlight,
		Link.configure({
			openOnClick: true,
			autolink: true,
			defaultProtocol: "https",
		}),
		Mathematics.configure({
			katexOptions: {
				throwOnError: false,
			},
		}),
		TextAlign.configure({
			types: ["heading", "paragraph"],
		}),
		TaskList,
		TaskItem.configure({
			nested: true,
		}),
		TableKit.configure({
			table: {
				lastColumnResizable: false,
				resizable: true,
			},
		}),
	];
}

const tiptapDocumentSchema = getSchema(getTiptapDocumentSchemaExtensions());

export function getTiptapDocumentSchema() {
	return tiptapDocumentSchema;
}
